"use strict";
const D=JSON.parse(document.getElementById("report-data").textContent),$=id=>document.getElementById(id);
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const value=v=>v===null||v===undefined?"미확인":esc(v),axisLabels={H:"대상•원형형",E:"의미•이미지형",R:"자기•몰입형"};
const conditionNames={A0:"A0 · 텍스트",A1:"A1 · 사진 E/R",A2:"A2 · 조건부 H 사진",A3:"A3 · SNS 건수",A4:"A4 · SNS 건수·의미"};
const photoNames={visual_character:"시각적 성격",natural_setting:"자연 환경",traditional_appearance:"전통적 외관"};
const sourceNames={KorService2:"한국관광공사",Odii:"오디오 해설",PhotoGalleryService1:"관광사진",APIFY_INSTAGRAM:"인스타그램"};
const roleNames={OFFICIAL_DESCRIPTION:"공식 설명",OFFICIAL_NARRATIVE:"공식 서사",OFFICIAL_PHOTO:"공식 사진",UNCLASSIFIED:"작성 주체 미확인",ADVERTISEMENT:"광고 표시 게시물",OFFICIAL_PROMOTION:"공식 홍보",VISITOR_POST:"방문자 게시물"};
const href=u=>{try{return new URL(u).protocol==="https:"?esc(u):""}catch{return ""}};
const photoSource=p=>/^photos\/[a-f0-9]{64}\.(jpg|png|webp|gif)$/.test(p.image_file??"")?p.image_file:href(p.url);
const allNames=new Map(Object.values(D.datasets).flatMap(d=>d.rows).map(r=>[r.id,r.name]));
window.itdaDetails=Object.create(null);let page=0,currentCase=null;
$("completion").textContent=D.final?"전수 2,000곳의 새 분석과 AI 검토 산출물을 포함한 보고서입니다.":"전수 재분석이 진행 중입니다. 개발·새 평가 결과와 기존 2,000곳 목록을 먼저 제공합니다.";
$("theory-content").innerHTML=D.theory.map(t=>`<details><summary>${esc(t.axis)} ${esc(axisLabels[t.axis])} · ${esc(t.theory)}</summary>${t.facets.map(f=>`<div class="facet-block"><h3>${esc(f.key)} ${esc(f.title)}</h3><p>${esc(f.question)}</p><p class="note">반례: ${esc(f.counterexample)}</p><ol start="0">${f.anchors.map(a=>`<li>${esc(a)}</li>`).join("")}</ol></div>`).join("")}</details>`).join("");
function dataset(){return D.datasets[$("dataset").value]}
function categoryOptions(){const labels=[...new Set(dataset().rows.map(r=>r.category))].sort();$("category").innerHTML='<option value="">모든 유형</option>'+labels.map(x=>`<option>${esc(x)}</option>`).join("")}
function renderPlaces(){const q=$("search").value.trim().toLocaleLowerCase(),cat=$("category").value,coverage=$("coverage").value;const rows=dataset().rows.filter(r=>(!q||(r.name+" "+r.region).toLocaleLowerCase().includes(q))&&(!cat||r.category===cat)&&(!coverage||(coverage==="3"?r.axes&&Object.values(r.axes).every(v=>v!==null):!r.axes||Object.values(r.axes).some(v=>v===null))));page=Math.min(page,Math.max(0,Math.ceil(rows.length/20)-1));$("places").innerHTML=rows.slice(page*20,page*20+20).map(r=>`<tr><td>${r.conditions?`<button class="pick" data-place="${esc(r.id)}">${esc(r.name)}</button>`:esc(r.name)}</td><td>${esc(r.region)}<div class="note">${esc(r.category)}</div></td><td>${r.conditions?"새 분석 있음":'<span class="pending">새 분석 대기</span>'}</td>${["H","E","R"].map(a=>`<td class="num">${value(r.axes?.[a])}</td>`).join("")}</tr>`).join("")||'<tr><td colspan="6" class="empty">조건에 맞는 장소가 없습니다.</td></tr>';$("count").textContent=`${rows.length.toLocaleString()}곳 · ${rows.length?page*20+1:0}–${Math.min(rows.length,(page+1)*20)}번째`;$("page-label").textContent=`${rows.length?page+1:0} / ${Math.ceil(rows.length/20)}쪽`;$("prev").disabled=page===0;$("next").disabled=(page+1)*20>=rows.length;$("places").querySelectorAll("[data-place]").forEach(b=>b.onclick=()=>selectCase(b.dataset.place,true))}
function caseOptions(){const available=dataset().rows.filter(r=>r.conditions),representative=available.filter(r=>D.representatives.includes(r.id)),other=available.filter(r=>!D.representatives.includes(r.id)),rows=[...representative,...other];const options=rs=>rs.map(r=>`<option value="${esc(r.id)}">${esc(r.name)}</option>`).join("");$("case-select").innerHTML=(representative.length?`<optgroup label="기존 감사에서 고른 경계 사례">${options(representative)}</optgroup>`:"")+`<optgroup label="다른 장소">${options(other)}</optgroup>`;if(rows.length)selectCase(rows[0].id,false);else{$("condition").innerHTML="";$("case-body").innerHTML='<p>이 묶음은 전수 검토 완료 후 새 근거를 공개합니다. 개발·새 평가 묶음에서 완료된 사례를 살펴보세요.</p>';currentCase=null}}
function selectCase(id,scroll){const row=dataset().rows.find(r=>r.id===id);if(!row?.conditions)return;currentCase=row;$("case-select").value=id;$("condition").innerHTML=Object.keys(row.conditions).map(c=>`<option value="${c}">${conditionNames[c]}</option>`).join("");$("condition").value="A1";loadCase();if(scroll)$("cases").scrollIntoView({block:"start"})}
function loadCase(){const row=currentCase,c=$("condition").value,entry=row?.conditions[c];if(!entry)return;$("case-body").textContent="원문과 사진 관찰 기록을 불러오고 있습니다.";if(window.itdaDetails[entry.hash])return renderCase(window.itdaDetails[entry.hash]);const script=document.createElement("script");script.src=entry.file;script.onload=()=>{script.remove();if(currentCase===row&&$("condition").value===c)renderCase(window.itdaDetails[entry.hash])};script.onerror=()=>{script.remove();if(currentCase===row&&$("condition").value===c)$("case-body").innerHTML='<p>상세 파일을 읽지 못했습니다. 보고서의 data 폴더가 함께 있는지 확인해 주세요.</p>'};document.body.append(script)}
function renderCase(a){if(!a)return;const row=currentCase;$("case-body").innerHTML=`<h3>${esc(a.name)}</h3><p>${esc(a.address)}</p><div class="axis-readout">${["H","E","R"].map(k=>`<strong>${axisLabels[k]} ${value(a.axes[k])}</strong>`).join("")}</div>${row.legacy?`<p class="note">이전 정의의 기록: H ${value(row.legacy.H)} / E ${value(row.legacy.E)} / R ${value(row.legacy.R)}. 새 숫자와 같은 척도의 개선량으로 비교하지 않습니다.</p>`:""}<div class="image-grid">${a.photos.map((p,index)=>`<figure>${photoSource(p)?`<img src="${photoSource(p)}" alt="${esc(a.name)}의 공식 사진" loading="lazy" width="320" height="220">`:""}<figcaption class="note"><strong>사진 ${index+1}</strong> · ${esc(p.attribution)} · 공공누리 제1유형<br>${p.reviews.map(r=>`${esc(photoNames[r.key]??r.key)}: ${esc({SUPPORTED:"AI 지지",REJECTED:"AI 거부",UNCERTAIN:"AI 미확정"}[r.decision])}`).join(" · ")}</figcaption><details><summary>이 사진의 관찰·검토</summary>${p.observations.map(o=>`<p class="note"><strong>${esc(photoNames[o.key]??o.key)}</strong> · 제안 ${value(o.level)}/4<br>${esc(o.reason)}<br>AI 검토: ${esc(p.reviews.find(r=>r.key===o.key)?.reason??"미검토")}</p>`).join("")}</details></figure>`).join("")}</div><p class="note">사진은 보이는 분위기·외관·환경만 다룹니다. 같은 모델의 별도 검토는 사람 정답이 아닙니다. 사진이 없다는 것은 해당 경험이 0점이라는 뜻이 아닙니다.</p>${a.facets.map(f=>`<details><summary>${esc(f.key)} ${esc(D.facets[f.key])} · ${value(f.value)}</summary><p class="reading">${esc(f.reason)}</p>${f.contributions.map(c=>`<h4>${esc({TEXT:"텍스트",PHOTO:"사진 관찰",SOCIAL:"SNS 관측"}[c.channel])} · 기여 ${c.weight_bp/100}%</h4>${c.evidence.map(e=>`${e.quote?`<blockquote>${esc(e.quote)}</blockquote>`:""}${e.observation?`<p><strong>사진 ${a.photos.findIndex(p=>p.image_sha256===e.image_sha256)+1}</strong> · ${esc(e.observation)}</p>`:""}${e.count!==null&&e.count!==undefined?`<p>관측 태그 게시물 수: ${Number(e.count).toLocaleString()}건</p>`:""}<p class="note">${esc(sourceNames[e.provider]??e.provider)} · ${esc(roleNames[e.role]??e.role)} · 수집 ${esc(e.at.slice(0,10))}${href(e.uri)?` · <a href="${href(e.uri)}" target="_blank" rel="noreferrer">원 출처</a>`:""}</p>`).join("")}`).join("")}${f.missing.length?`<p class="note">미확인 채널: ${f.missing.map(x=>esc({TEXT:"텍스트",PHOTO:"사진",SOCIAL:"SNS"}[x])).join(", ")}</p>`:""}</details>`).join("")}<details><summary>재현 식별자</summary><p class="versions">평가 ${esc(a.hash)}<br>출처 ${esc(a.source_hash)}<br>정책 ${esc(a.policy_hash)}</p></details>`}
const ranks=ids=>`<ol>${ids.map(id=>`<li>${esc(allNames.get(id)??id)}</li>`).join("")}</ol>`;
function scenarioOptions(){const plan=D.experiments[$("experiment-data").value];$("scenario").innerHTML=plan.scenarios.map((s,i)=>`<option value="${i}">${esc(s.label)}</option>`).join("");renderExperiment()}
function renderExperiment(){const group=D.experiments[$("experiment-data").value],s=group.scenarios[Number($("scenario").value)];$("experiment-body").innerHTML=`<p class="note">${esc(s.description)}</p><p class="note">좁은 화면에서는 표를 가로로 이동해 Top 5를 볼 수 있습니다.</p><div class="table-wrap" tabindex="0" aria-label="출처 조건별 추천 비교"><table class="experiment-table"><thead><tr><th>조건</th><th>추천 자격</th><th>실제 Top 5</th></tr></thead><tbody>${Object.entries(s.runs).map(([name,r])=>`<tr><td>${esc(conditionNames[name])}</td><td>${r.eligible_count}/${group.places}곳</td><td class="compare-cell">${ranks(r.items.map(i=>i.place_id))}${r.items.length?"":"확인 가능한 후보 없음"}</td></tr>`).join("")}</tbody></table></div><details><summary>공통 자격 후보에서의 변화</summary>${s.comparisons.map(c=>`<p>${esc(c.first)}→${esc(c.second)} · 공통 자격 ${c.common_eligible??"별도 기록"}곳 · Top 5 겹침 ${c.common.shared}곳 · 순서 ${c.common.same_order?"동일":"변경"}</p>`).join("")}</details>`}
$("limits-content").innerHTML=D.limitations.map(x=>`<p>${esc(x)}</p>`).join("");$("lineage").innerHTML=Object.entries(D.lineage).map(([k,v])=>`<p><strong>${esc(k)}</strong><br>${esc(typeof v==="string"?v:JSON.stringify(v))}</p>`).join("");
$("dataset").onchange=()=>{page=0;categoryOptions();renderPlaces();caseOptions()};for(const id of ["search","category","coverage"])$(id).addEventListener(id==="search"?"input":"change",()=>{page=0;renderPlaces()});$("prev").onclick=()=>{page--;renderPlaces()};$("next").onclick=()=>{page++;renderPlaces()};$("case-select").onchange=()=>selectCase($("case-select").value,false);$("condition").onchange=loadCase;$("experiment-data").onchange=scenarioOptions;$("scenario").onchange=renderExperiment;categoryOptions();renderPlaces();caseOptions();scenarioOptions();
